Fix `syn` version in `defmt-macros`
The previous version gives us following error:
```text
error: failed to select a version for `syn`.
    ... required by package `defmt-macros v0.3.2 (/github.com/knurling-rs/defmt/macros)`
    ... which satisfies path dependency `defmt-macros` (locked to 0.3.2) of package `defmt v0.3.2 (/github.com/knurling-rs/defmt/defmt)`
    ... which satisfies path dependency `defmt` (locked to 0.3.2) of package `defmt-rtt v0.3.2 (/github.com/knurling-rs/defmt/firmware/defmt-rtt)`
    ... which satisfies dependency `defmt-rtt = "^0.3"` (locked to 0.3.2) of package `krate v0.1.0 (/github.com/knurling-rs/krate)`
versions that meet the requirements `^1.0.100` are: 1.0.101, 1.0.100

all possible versions conflict with previously selected packages.

  previously selected package `syn v1.0.95`
    ... which satisfies dependency `syn = "^1.0"` (locked to 1.0.95) of package `cortex-m-rt-macros v0.7.0`
    ... which satisfies dependency `cortex-m-rt-macros = "=0.7.0"` (locked to 0.7.0) of package `cortex-m-rt v0.7.1`
    ... which satisfies dependency `cortex-m-rt = "^0.7"` (locked to 0.7.1) of package `defmt-test v0.3.0 (/github.com/knurling-rs/defmt/firmware/defmt-test)`
    ... which satisfies dependency `defmt-test = "^0.3"` (locked to 0.3.0) of package `krate v0.1.0 (/github.com/knurling-rs/krate)`

failed to select a version for `syn` which could resolve this conflict
```